cls
Write-Host ""
Write-Host ""
Write-Host ""
Write-Host ""
Write-Host ""
Write-Host ""
Write-Host ""
Write-Host ""
Write-Host ""
Write-Host ""
Write-Host ""
Write-Host ""
Write-Host "Ransomware is your friend"
Write-Host ""
Write-Host ""
Write-Host "                  uuuuuuu                    "
Write-Host "              uu%%%%%%%%%%%uu                "
Write-Host "           uu%%%%%%%%%%%%%%%%%uu             "
Write-Host "          u%%%%%%%%%%%%%%%%%%%%%u            "
Write-Host "         u%%%%%%%%%%%%%%%%%%%%%%%u           "
Write-Host "        u%%%%%%%%%%%%%%%%%%%%%%%%%u          "
Write-Host "        u%%%%%%%%%%%%%%%%%%%%%%%%%u          "
Write-Host "        u%%%%%%'   '%%%'   '%%%%%%u          "
Write-Host "        '%%%%'      u%u       %%%%'          "
Write-Host "         %%%u       u%u       u%%%           "
Write-Host "         %%%u      u%%%u      u%%%           "
Write-Host "          '%%%%uu%%%   %%%uu%%%%'            "
Write-Host "           '%%%%%%%'   '%%%%%%%'             "
Write-Host "             u%%%%%%%u%%%%%%%u               "
Write-Host "              u%'%'%'%'%'%'%u                "
Write-Host "   uuu        %%u% % % % %u%%       uuu      "
Write-Host "  u%%%%        %%%%%u%u%u%%%       u%%%%     "
Write-Host "   %%%%%uu      '%%%%%%%%%'     uu%%%%%%     "
Write-Host " u%%%%%%%%%%%uu    '''''    uuuu%%%%%%%%%%   "
Write-Host " %%%%'''%%%%%%%%%%uuu   uu%%%%%%%%%'''%%%'   "
Write-Host "  '''      ''%%%%%%%%%%%uu ''%'''            "
Write-Host "            uuuu ''%%%%%%%%%%uuu             "
Write-Host "   u%%%uuu%%%%%%%%%uu ''%%%%%%%%%%%uuu%%%    "
Write-Host "   %%%%%%%%%%''''           ''%%%%%%%%%%%'   "
Write-Host "    '%%%%%'                      ''%%%%''    "
Write-Host "      %%%'                         %%%%'     "
Write-Host ""
Write-Host ""
Write-Host ""
Write-Host ""
for ($i = 1; $i -le 100; $i++ )
{
    Write-Progress -Activity "Encrypting C:\" -Status "$i% Complete:" -PercentComplete $i;
    Start-Sleep -Seconds 1
}
